[package]
name = "encre-css"
version = "0.20.1"
description = "A TailwindCSS-compatible utility-first CSS generation library written in Rust"
license = "MIT"
edition = "2021"
repository = "https://gitlab.com/encre-org/encre-css.git"
documentation = "https://docs.rs/encre-css"
readme.workspace = true
keywords = ["tailwind", "css", "compiler"]
categories = ["web-programming"]

[[bench]]
name = "benchmark"
harness = false

[dependencies]
toml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
phf = { version = "0.13.1", features = ["macros"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
criterion = { version = "0.7.0", features = ["html_reports"] }
