[package]
name = "encre-css-typography"
version = "0.6.1"
description = "Define beautiful typographic defaults for HTML you don't control"
license = "MIT"
edition = "2021"
repository = "https://gitlab.com/encre-org/encre-css.git"
documentation = "https://docs.rs/encre-css-typography"
keywords = ["tailwind", "css", "compiler", "encre-css"]
categories = ["web-programming"]

[dependencies]
encre-css = { path = "../encre-css", version = "0.21.0" }

[dev-dependencies]
pretty_assertions = "1.4.1"
