[package]
name = "encre-css-cli"
version = "0.21.0"
description = "A TailwindCSS-compatible utility-first CSS generation library written in Rust"
license = "MIT"
edition = "2021"
repository = "https://gitlab.com/encre-org/encre-css.git"
readme.workspace = true
keywords = ["tailwind", "css", "compiler", "cli"]
categories = ["web-programming", "command-line-utilities"]

[[bin]]
name = "encrecss"
path = "src/main.rs"

[dependencies]
encre-css = { path = "../encre-css", version = "0.20.1" }
clap = { version = "4.5.41", features = ["derive"] }
rand = "0.10.0"
wax = "0.7.0"
color-eyre = "0.6.5"
toml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
notify = "8.1.0"
encre-css-icons = { version = "0.7.1", path = "../encre-css-icons", optional = true }
encre-css-typography = { version = "0.6.1", path = "../encre-css-typography", optional = true }

[features]
encre-css-icons = ["dep:encre-css-icons"]
encre-css-typography = ["dep:encre-css-typography"]
