[package]
name = "encre-css-cli"
version = "0.20.0"
description = "A TailwindCSS-compatible utility-first CSS generation library written in Rust"
license = "MIT"
edition = "2021"
repository = "https://gitlab.com/encre-org/encre-css.git"
readme.workspace = true
keywords = ["tailwind", "css", "compiler", "cli"]
categories = ["web-programming", "command-line-utilities"]

[[bin]]
name = "encrecss"
path = "src/main.rs"

[dependencies]
encre-css = { path = "../encre-css", version = "0.20.0" }
clap = { version = "4.5.41", features = ["derive"] }
rand = "0.9.2"
wax = "0.6.0"
color-eyre = "0.6.5"
toml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
notify = "8.1.0"

